I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/story/chapter-one.rpy", line 68, in script call
    call decryption("a") from _call_decryption
  File "game/decryption_minigame_scripts/d_showSlots.rpy", line 8, in script call
    $ ui.interact()
  File "game/decryption_minigame_scripts/d_showSlots.rpy", line 8, in script call
    $ ui.interact()
  File "game/pac-scripts/guillermo_bedroom_pac.rpy", line 109, in script
    jump chapter_II_guillermo_bedroom_pac_handler
ScriptError: could not find label 'chapter_II_guillermo_bedroom_pac_handler'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/story/chapter-one.rpy", line 68, in script call
    call decryption("a") from _call_decryption
  File "game/decryption_minigame_scripts/d_showSlots.rpy", line 8, in script call
    $ ui.interact()
  File "game/decryption_minigame_scripts/d_showSlots.rpy", line 8, in script call
    $ ui.interact()
  File "game/pac-scripts/guillermo_bedroom_pac.rpy", line 109, in script
    jump chapter_II_guillermo_bedroom_pac_handler
  File "C:\Users\barba\OneDrive\Escritorio\renpy-8.3.2\renpy\ast.py", line 1699, in execute
    rv = renpy.game.script.lookup(target)
  File "C:\Users\barba\OneDrive\Escritorio\renpy-8.3.2\renpy\script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'chapter_II_guillermo_bedroom_pac_handler'.

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.2.24090902
a_golden_chance 1.0
Fri Nov 15 06:22:39 2024
