I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/story/chapter-one.rpy", line 68, in script call
    call decryption("a") from _call_decryption
  File "game/decryption_minigame_scripts/d_showSlots.rpy", line 8, in script call
    $ ui.interact()
  File "game/decryption_minigame_scripts/d_showSlots.rpy", line 8, in script call
    $ ui.interact()
  File "game/ui-buttons.rpy", line 31, in script
    return
Exception: Could not find return label ('game/story/chapter-one.rpy', 1731648005, 1).

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/story/chapter-one.rpy", line 68, in script call
    call decryption("a") from _call_decryption
  File "game/decryption_minigame_scripts/d_showSlots.rpy", line 8, in script call
    $ ui.interact()
  File "game/decryption_minigame_scripts/d_showSlots.rpy", line 8, in script call
    $ ui.interact()
  File "game/ui-buttons.rpy", line 31, in script
    return
  File "C:\Users\barba\OneDrive\Escritorio\renpy-8.3.2\renpy\ast.py", line 1493, in execute
    next_node(renpy.game.context().lookup_return(pop=True))
  File "C:\Users\barba\OneDrive\Escritorio\renpy-8.3.2\renpy\execution.py", line 744, in lookup_return
    raise Exception("Could not find return label {!r}.".format(self.return_stack[-1]))
Exception: Could not find return label ('game/story/chapter-one.rpy', 1731648005, 1).

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.2.24090902
a_golden_chance 1.0
Fri Nov 15 03:17:54 2024
